name: Lock Inactive Issues

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@f8a7d90315aeaafbccc7ebc73368aa4b933bb37c
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
